# Generated by Django 6.0.7 on 2026-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_massage_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
